/*
 * Copyright 2026 Peanut Butter Unicorn, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package lol.pbu.z4j.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.serde.annotation.Serdeable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * A set of properties which describe the standard::name field's autonumbering and uniqueness behavior. Autonumbering and uniqueness can't be used together
 *
 * @author Jonathan-Zollinger
 * @since 0.1.1
 */
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Data
@JsonPropertyOrder({
        CustomFieldProperties.JSON_PROPERTY_AUTOINCREMENT_ENABLED,
        CustomFieldProperties.JSON_PROPERTY_AUTOINCREMENT_NEXT_SEQUENCE,
        CustomFieldProperties.JSON_PROPERTY_AUTOINCREMENT_PADDING,
        CustomFieldProperties.JSON_PROPERTY_AUTOINCREMENT_PREFIX,
        CustomFieldProperties.JSON_PROPERTY_IS_UNIQUE,
})
@Serdeable
public class CustomFieldProperties {

    public static final String JSON_PROPERTY_AUTOINCREMENT_ENABLED = "autoincrement_enabled";
    public static final String JSON_PROPERTY_AUTOINCREMENT_NEXT_SEQUENCE = "autoincrement_next_sequence";
    public static final String JSON_PROPERTY_AUTOINCREMENT_PADDING = "autoincrement_padding";
    public static final String JSON_PROPERTY_AUTOINCREMENT_PREFIX = "autoincrement_prefix";
    public static final String JSON_PROPERTY_IS_UNIQUE = "is_unique";

    /**
     * Turns autonumbering on or off
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_AUTOINCREMENT_ENABLED)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean autoincrementEnabled;

    /**
     * The next number in the autonumbering sequence. It can't be negative or less than the current autonumbering value
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_AUTOINCREMENT_NEXT_SEQUENCE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Integer autoincrementNextSequence;

    /**
     * Sets the number of digits for autogenerated numbers. Valid values are 0-9
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_AUTOINCREMENT_PADDING)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Integer autoincrementPadding;

    /**
     * A prefix to autogenerated numbers that can't exceed 30 characters
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_AUTOINCREMENT_PREFIX)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String autoincrementPrefix;

    /**
     * Turns uniqueness on or off
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_IS_UNIQUE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean isUnique;

}
