name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_FILE: ${{ secrets.GPG_FILE }}
      GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@c2457a7fb283d2bfe1c94ac0c360c27a79bcffd4
      - name: Set up JDK
        uses: graalvm/setup-graalvm@03e8abf916fd0e281b2efe7b2da3378bb0a1d085
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0f4528296b4bc09e8ae0fc7be30185a4ab435545 # 6.0.0
      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_FILE: ${{ secrets.GPG_FILE }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: ./gradlew publishToMavenCentral --info