name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_FILE: ${{ secrets.GPG_FILE }}
      GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@342e94ec9aa7226938939f1ad2c761d1245996f5
      - name: Set up JDK
        uses: graalvm/setup-graalvm@9d0e2dff13a8c69a81d72a49c9816836f963fe01
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # 5.0.2
      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_FILE: ${{ secrets.GPG_FILE }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: ./gradlew publishToMavenCentral --info